org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=simple_music_control
mod.name=Simple Music Control
mod.group=me.pajic
mod.version=1.5.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=
mod.license=MIT
mod.description=Reduced delay between music tracks, next track keybind, creative music in survival, stop music on jukebox play
mod.sources_url=https://github.com/pajicadvance/simple-music-control
mod.homepage_url=https://modrinth.com/mod/simple_music_control
mod.issues_url=https://github.com/pajicadvance/simple-music-control/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]

publish.modrinth=8AX2hHnX
publish.curseforge=1185599
publish.github=false
