# general
mod.id = "simple_music_control"
mod.name = "Simple Music Control"
mod.group = "me.pajic"
mod.version = "1.5.2"
mod.description = "Reduced delay between music tracks, next track keybind, creative music in survival, stop music on jukebox play"
mod.authors = "pajic"
mod.contributors = ""
mod.license = "MIT"

# links
mod.sources_url = "https://github.com/pajicadvance/simple-music-control"
mod.homepage_url = "https://modrinth.com/mod/simple-music-control"
mod.issues_url = "https://github.com/pajicadvance/simple-music-control/issues"
mod.discord_url = "https://discord.gg/5RkzS66zWb"

# publishing
publish.modrinth = "8AX2hHnX"
publish.curseforge = "1185599"
publish.env.mr = "CLIENT_ONLY" #https://modmuss50.github.io/mod-publish-plugin/platforms/modrinth/#all-options
publish.env.cf.client = true
publish.env.cf.server = false
publish.dry_run = false

# loom
loomx.loom_version = "1.17-SNAPSHOT"

# dependencies
loader.fabric = "0.19.3"
dep.fzzy_config.coords = "me.fzzyhmstrs:$id:$version"
dep.fzzy_config.slug = "fzzy-config"
dep.sodium.coords = "net.caffeinemc:$id-$loader-api:$version"
dep.sodium_runtime.coords = "net.caffeinemc:sodium-$loader:$version"
dev.runtime_optionals = []

[fabric]
dep.fabric-api.coords = "net.fabricmc.fabric-api:$id:$version"
dep.modmenu.coords = "com.terraformersmc:$id:$version"

[neoforge]


["1.21.1"]
mod.mc_releases = ["1.21", "1.21.1"]
loader.neo = "21.1.244"
optional.sodium = "0.8.12+mc1.21.1"
runtime.sodium_runtime = "0.8.12+mc1.21.1"

[fabric."1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
required.fabric-api = "0.116.14+1.21.1"
required.fzzy_config = "0.7.6+1.21"
runtime.modmenu = "11.0.4"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
required.fzzy_config = "0.7.6+1.21+neoforge"


["26.1"]
mod.mc_releases = ["26.1", "26.1.1", "26.1.2"]
loader.neo = "26.1.2.87"
optional.sodium = "0.9.1+mc26.1.2"
runtime.sodium_runtime = "0.9.1+mc26.1.2"

[fabric."26.1"]
mod.mc_compat = "~26.1"
required.fabric-api = "0.155.2+26.1.2"
required.fzzy_config = "0.7.6+26.1-pre-3"
runtime.modmenu = "18.0.0"

[neoforge."26.1"]
mod.mc_compat = "[26.1, 26.2)"
required.fzzy_config = "0.7.6+26.1-pre-3+neoforge"


["26.2"]
mod.mc_releases = ["26.2"]
loader.neo = "26.2.0.36-beta"
optional.sodium = "0.9.1+mc26.2"
runtime.sodium_runtime = "0.9.1+mc26.2"

[fabric."26.2"]
mod.mc_compat = "~26.2"
required.fabric-api = "0.155.2+26.2"
required.fzzy_config = "0.7.6+26.2-pre-3"
runtime.modmenu = "20.0.1"

[neoforge."26.2"]
mod.mc_compat = "[26.2, 26.3)"
required.fzzy_config = "0.7.6+26.2+neoforge"


["26.3"]
mod.mc_releases = ["26.3-pre.1"]
#loader.neo = "26.2.0.36-beta"
dep.mixson.coords = "maven.modrinth:$id:$version"
required.mixson = "2.2.0"
optional.sodium = "0.9.1+mc26.2"
#runtime.sodium_runtime = "0.9.1+mc26.2"

[fabric."26.3"]
mod.mc_compat = "~26.3"
required.fabric-api = "0.159.1+26.3"
required.fzzy_config = "0.7.6+26.2-pre-3"
#runtime.modmenu = "20.0.1"

#[neoforge."26.2"]
#mod.mc_compat = "[26.3, 26.4)"
#required.fzzy_config = "0.7.6+26.2+neoforge"
