package me.pajic.simple_music_control.config;

import dev.kikugie.fletching_table.annotation.fabric.Entrypoint;
import me.pajic.simple_music_control.SMC;
import me.pajic.simple_music_control.gui.WidgetPosition;
import net.caffeinemc.mods.sodium.api.config.ConfigEntryPoint;
import net.caffeinemc.mods.sodium.api.config.structure.ConfigBuilder;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;

//? neoforge {
/*import net.caffeinemc.mods.sodium.api.config.ConfigEntryPointForge;

@ConfigEntryPointForge(SMC.MOD_ID)
*///?}
@SuppressWarnings("unused")
@Entrypoint("sodium:config_api_user")
public class ModSodiumConfig implements ConfigEntryPoint {

    @Override
    public void registerConfigLate(ConfigBuilder builder) {
        builder.registerOwnModOptions()
                .setName("Simple Music Control")
                .setColorTheme(builder.createColorTheme().setBaseThemeRGB(0x7F704F))
                .setNonTintedIcon(Identifier.parse("simple_music_control:textures/config_icon.png"))
                .addPage(builder.createOptionPage()
                        .setName(Component.translatable("simple_music_control.config.settings"))
                        .addOption(builder.createBooleanOption(SMC.id("stop_music_on_jukebox_use"))
                                .setName(Component.translatable("simple_music_control.config.stopMusicOnJukeboxUse"))
                                .setTooltip(Component.translatable("simple_music_control.config.stopMusicOnJukeboxUse"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.stopMusicOnJukeboxUse.validateAndSet(bl), () -> SMC.CONFIG.stopMusicOnJukeboxUse.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("creative_music_in_survival"))
                                .setName(Component.translatable("simple_music_control.config.creativeMusicInSurvival"))
                                .setTooltip(Component.translatable("simple_music_control.config.creativeMusicInSurvival"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.creativeMusicInSurvival.validateAndSet(bl), () -> SMC.CONFIG.creativeMusicInSurvival.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("situational_music_in_creative"))
                                .setName(Component.translatable("simple_music_control.config.situationalMusicInCreative"))
                                .setTooltip(Component.translatable("simple_music_control.config.situationalMusicInCreative"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.situationalMusicInCreative.validateAndSet(bl), () -> SMC.CONFIG.situationalMusicInCreative.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createIntegerOption(SMC.id("music_min_delay"))
                                .setName(Component.translatable("simple_music_control.config.musicMinDelay"))
                                .setTooltip(Component.translatable("simple_music_control.config.musicMinDelay"))
                                .setDefaultValue(0)
                                .setValueFormatter(value -> Component.translatable("simple_music_control.config.seconds", value))
                                .setRange(0, 2400, 20)
                                .setBinding(i -> SMC.CONFIG.musicMinDelay.validateAndSet(i), () -> SMC.CONFIG.musicMinDelay.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createIntegerOption(SMC.id("music_max_delay"))
                                .setName(Component.translatable("simple_music_control.config.musicMaxDelay"))
                                .setTooltip(Component.translatable("simple_music_control.config.musicMaxDelay"))
                                .setDefaultValue(600)
                                .setValueFormatter(value -> Component.translatable("simple_music_control.config.seconds", value))
                                .setRange(0, 2400, 20)
                                .setBinding(i -> SMC.CONFIG.musicMaxDelay.validateAndSet(i), () -> SMC.CONFIG.musicMaxDelay.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("play_music_when_paused"))
                                .setName(Component.translatable("simple_music_control.config.playMusicWhenPaused"))
                                .setTooltip(Component.translatable("simple_music_control.config.playMusicWhenPaused"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.playMusicWhenPaused.validateAndSet(bl), () -> SMC.CONFIG.playMusicWhenPaused.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("now_playing_widget"))
                                .setName(Component.translatable("simple_music_control.config.nowPlayingWidget"))
                                .setTooltip(Component.translatable("simple_music_control.config.nowPlayingWidget"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.nowPlayingWidget.validateAndSet(bl), () -> SMC.CONFIG.nowPlayingWidget.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createIntegerOption(SMC.id("now_playing_widget_duration"))
                                .setName(Component.translatable("simple_music_control.config.nowPlayingWidgetDuration"))
                                .setTooltip(Component.translatable("simple_music_control.config.nowPlayingWidgetDuration"))
                                .setDefaultValue(6)
                                .setValueFormatter(value -> Component.translatable("simple_music_control.config.seconds", value))
                                .setRange(1, 30, 1)
                                .setBinding(i -> SMC.CONFIG.nowPlayingWidgetDuration.validateAndSet(i), () -> SMC.CONFIG.nowPlayingWidgetDuration.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("show_now_playing_widget_in_pause_menu"))
                                .setName(Component.translatable("simple_music_control.config.showNowPlayingWidgetInPauseMenu"))
                                .setTooltip(Component.translatable("simple_music_control.config.showNowPlayingWidgetInPauseMenu"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.showNowPlayingWidgetInPauseMenu.validateAndSet(bl), () -> SMC.CONFIG.showNowPlayingWidgetInPauseMenu.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("show_now_playing_widget_on_title_screen"))
                                .setName(Component.translatable("simple_music_control.config.showNowPlayingWidgetOnTitleScreen"))
                                .setTooltip(Component.translatable("simple_music_control.config.showNowPlayingWidgetOnTitleScreen"))
                                .setDefaultValue(true)
                                .setBinding(bl -> SMC.CONFIG.showNowPlayingWidgetOnTitleScreen.validateAndSet(bl), () -> SMC.CONFIG.showNowPlayingWidgetOnTitleScreen.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createEnumOption(SMC.id("pause_widget_position"), WidgetPosition.class)
                                .setName(Component.translatable("simple_music_control.config.pauseWidgetPosition"))
                                .setTooltip(Component.translatable("simple_music_control.config.pauseWidgetPosition"))
                                .setDefaultValue(WidgetPosition.TOP_LEFT)
                                .setElementNameProvider(WidgetPosition::getName)
                                .setBinding(e -> SMC.CONFIG.pauseWidgetPosition.validateAndSet(e), () -> SMC.CONFIG.pauseWidgetPosition.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createEnumOption(SMC.id("title_widget_position"), WidgetPosition.class)
                                .setName(Component.translatable("simple_music_control.config.titleWidgetPosition"))
                                .setTooltip(Component.translatable("simple_music_control.config.titleWidgetPosition"))
                                .setDefaultValue(WidgetPosition.TOP_LEFT)
                                .setElementNameProvider(WidgetPosition::getName)
                                .setBinding(e -> SMC.CONFIG.titleWidgetPosition.validateAndSet(e), () -> SMC.CONFIG.titleWidgetPosition.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createBooleanOption(SMC.id("unlock_situational_music"))
                                .setName(Component.translatable("simple_music_control.config.unlockSituationalMusic"))
                                .setTooltip(Component.translatable("simple_music_control.config.unlockSituationalMusic.desc"))
                                .setDefaultValue(false)
                                .setBinding(bl -> SMC.CONFIG.unlockSituationalMusic.validateAndSet(bl), () -> SMC.CONFIG.unlockSituationalMusic.get())
                                .setStorageHandler(SMC.CONFIG::save))
                        .addOption(builder.createIntegerOption(SMC.id("situational_music_chance"))
                                .setName(Component.translatable("simple_music_control.config.situationalMusicChance"))
                                .setTooltip(Component.translatable("simple_music_control.config.situationalMusicChance.desc"))
                                .setDefaultValue(70)
                                .setValueFormatter(value -> Component.literal(value + "%"))
                                .setRange(1, 100, 1)
                                .setBinding(i -> SMC.CONFIG.situationalMusicChance.validateAndSet(i), () -> SMC.CONFIG.situationalMusicChance.get())
                                .setStorageHandler(SMC.CONFIG::save))
                );
    }
}
